
use supply_chain;

select * from supply_chain_data limit 5;

#TOTAL REVENUE GENERATED BY PRODUCT TYPE

SELECT
    `Product type`,
    SUM(`revenue generated`) AS total_revenue
FROM supply_chain_data
GROUP BY `Product type`;     
 #(Most of revenue is generated from skincare products and then by haircare and then by cosmetics)

#SHIPPING COSTS BY CARRIER

SELECT 
     `Shipping carriers`,
     AVG(`Shipping costs`) as shipping_cost
FROM supply_chain_data
GROUP BY `Shipping carriers`;
  #(Carrier C is more cost effective and then Carrier A and then Carrier B)
  
#AVERAGE LEAD TIMES BY SUPPLIER

SELECT 
    `Supplier name`,
    ROUND(AVG(`Lead time`),2) as Avg_lead_time
FROM supply_chain_data
GROUP BY `Supplier name` 
ORDER BY Avg_lead_time ;
   # (Supplier 3 is assesing more reliability in delivering products on time).

#TOTAL PRODUCTS SOLD BY LOCATION (To understand regional demand)

SELECT 
     `Location`,
     SUM(`Number of products sold`) as Products_sold_by_location
FROM supply_chain_data
GROUP BY `Location`
ORDER BY `Products_sold_by_location` DESC;
   #(Most products are sold in Kolkata)

# AVERAGE DEFECT RATES BY INSPECTION RESULTS TO ASSESS PRODUCT QUALITY

SELECT 
     `Inspection results`,
     ROUND(AVG(`Defect rates`),2) as Defect_Rate 
FROM supply_chain_data
GROUP BY `Inspection results`
order by Defect_rate desc;
   #(Inspection Result 'fail' has most defect rate)
   
# RANKING PRODUCTS BY PPROFITABILITY(Revenue Generated-Manufacturing Costs-Shipping Costs

SELECT  
     SKU, 
     `Product type`, 
     ROUND((`Revenue generated` - `Manufacturing costs` - `Shipping costs`),2) AS Profitability, 
	 DENSE_RANK() OVER(PARTITION BY  `Product type` ORDER BY `Revenue generated`, `Manufacturing costs`, `Shipping costs` DESC) 
AS Profitability_Rank 
FROM supply_chain_data;

# TOP SHIPPING CARRIERS FOR EVERY PRODUCT

SELECT 
`Product type` , `Shipping carriers`, avg_shippingcost
FROM(
  SELECT 
      `Product type`,
      `Shipping carriers`,
	  ROUND(AVG(`Shipping costs`),2) AS avg_shippingcost, 
	  DENSE_RANK() OVER(PARTITION BY `Product type` ORDER BY AVG(`Shipping costs`)) AS drank
  FROM supply_chain_data
  GROUP BY `Shipping carriers`, `Product type`
) AS tab WHERE drank=1;
     #(for cosmetics- carrier C is cost effective
     #  for haircare- carrier B is cost effective
	 #  for skincare- carrier B is cost effective)

  #SUPPLIER PERFORMANCE ANALYSIS
  
SELECT 
    `Supplier name`,
    AVG(`Lead times`) AS avg_lead_time
FROM supply_chain_data
GROUP BY `Supplier name`
HAVING AVG(`Lead times`) >
       (SELECT AVG(`Lead times`) FROM supply_chain_data);
       
	#Suppliers 1,2,4 are the suppliers with lead times higher than the overall average
